### ISSUE TITLE
 Standard names: *time varying ocean gridbox thickness*

### ISSUE THREAD

**Issue by jmecki** [cf-convention/vocabularies#220]
Before submitting an issue be sure you have read and understood the [rules for vocabulary changes](http://cfconventions.org/standard_name_rules.html) and review the [guidance for constructing standard names](http://cfconventions.org/Data/cf-standard-names/docs/guidelines.html)

Please note that it is fine to group together a number of proposals in a single GitHub issue (i.e. it is not necessary to open a separate issue for each vocabulary term). Change proposals should include the following information as applicable.

**Proposer's name**
Jenny Mecking

**Date**
Sept. 8, 2024

For each term please try to give the following:

**- Term**
ocean_gridcell_thickness_on_t_points

**- Description**
Time varying ocean gridbox thickness at t points.

**- Units**
m

**- Term**
ocean_gridcell_thickness_on_u_points

**- Description**
Time varying ocean gridbox thickness at u points.

**- Units**
m

**- Term**
ocean_gridcell_thickness_on_v_points

**- Description**
Time varying ocean gridbox thickness at v points.

**- Units**
m

**Comment by JonathanGregory** [comment]
Dear Jenni @jmecki 

There is an existing standard name `cell_thickness` which would be appropriate for ocean gridcell thickness. In CF terms, the description of the grid is not part of the standard name, because a geophysical quantity is always the same thing, regardless of the grid. The coordinate variables define the grid. You could use the `long_name` if you want to describe which grid a variable is on.

Best wishes

Jonathan

**Comment by jmecki** [comment]
Thanks Jonathan.  That makes sense, it is also possible to compute the thickness on u and v points if you know the Arakawa grid the model uses.  I'm happy to have this one closed without a new name being generated.
