### ISSUE TITLE
 Standard names: Propose new names for sea ice biogeochemical parameters for use in SIMIP and CMIP7

### ISSUE THREAD

**Issue by letitede** [cf-convention/vocabularies#223]
As discussed within the Sea Ice Model Intercomparison Project (SIMIP) for CMIP7, I would like to propose some new standard names in relation to sea-ice biogeochemistry. 

Name: sichl
Title: Amount of Total Ice Algae Expressed as Chlorophyll in Sea Ice
CF Standard Name: amount_ice_algae_expressed_as_chlorophyll_in_sea_ice
Units: Kg m-2
Description: Sum of chlorophyll from all ice algal group concentrations.

Name: sic 
Title: Total Ice Algal Carbon Amount
CF Standard Name: mole_content_of_ice_algae_expressed_as_carbon_in_sea_ice
Units: mol m-2
Description: Sum of ice algal carbon component content.

Name: sino3
Title: Dissolved Nitrate Amount in Sea Ice
CF Standard Name: mole_amount_of_nitrate_in_sea_ice
Units: mol m-2
Description: Mole amount means moles of substance per unit area.

Name: sisi
Title: Dissolved Silicon Amount in Sea Ice
CF Standard Name: mole_amount_of_silicon_in_sea_ice
Units: mol m-2
Description: Mole amount means moles of substance per unit area.

Name: sigpp
Title: Gross primary production in sea ice as carbon amount flux
CF Standard Name: gross_primary_productivity_of_biomass_expressed_as_carbon_in_sea_ice
Units: kg m-2 s
Description: Total GPP of ice algae in sea ice.

Thanks for considering this proposal.

Proposer's name: Letizia Tedesco
Date: 12 September 2024

**Comment by taylor13** [comment]
Regarding Jonathan's rewording ..."due to ice algae in sea ice".   Are there any other kinds of algae in sea ice?  If not, perhaps "due to algae in sea ice" would do.
Karl

**Comment by letitede** [comment]
Dear Jonathan @JonathanGregory,
Dear Karl @taylor13 ,

Thank you for your feedback.

I apologize if the terminology used for the new variables was not entirely appropriate.

Regarding your suggestions, they all make sense.

As for the term "ice algae" vs. just "algae," I agree that if the environment is understood (i.e., sea ice in our case), using "algae" alone could suffice. However, "ice algae" leaves no room for ambiguity, and I would recommend keeping it for clarity and consistency. 

As for the units for GPP, you are right, Jonathan — I missed a -1 in my initial proposal. kg m-2 s-1 is indeed correct.

Thank you both!

Kind regards,
Letizia

**Comment by roy-lowry** [comment]
The term 'ice algae' is unfamiliar to me, but its meaning is clear - especially out of context with the rest of the Standard Name - and so I have no problem with its use.

Roy.

**Comment by lhmarsden** [comment]
My personal opinion is that it should be `algae` instead of `ice_algae`, for a few reasons.

- I guess most/all algae in sea ice is "ice algae". But if not, is the data provider sure whether all the species are "ice algae" or not? Do all algae that live in ice live uniquely in ice, and vice versa? Where is the line here? 
- `sea_ice_mass_content_of_algae_expressed_as_chlorophyll` would be worded more similarly to hypothetical future standard names like `sea_water_mass_content_of_algae_expressed_as_chlorophyll` 
- What if the algae is not "ice_algae"? A name like `sea_ice_mass_content_of_other_algae_expressed_as_chlorophyll` is not very neat, and we would probably need to revert to `sea_ice_mass_content_of_algae_expressed_as_chlorophyll` for such data anyway.

This reminds me a bit of the `sea_water` vs just `water` issue. I heard some talk at the CF workshop that it may have been better with hindsight to use just `water` because now new standard names need to be proposed for lake/terrestrial water. Similar with `land_ice` which is used for glaciers, but what if the glacier extends over the sea, which is often the case?

So my preference would be for the more generalised term in this case.

**Comment by roy-lowry** [comment]
The term 'ice algae' conveys to me algae that survive in ice.  I can see it possibly being used to partition algae in sea water in a modelling, but not observational, context as I can't see anybody trying to aggregate individual species measurements. I can't think of a use case for describing the algae that wouldn't survive in ice.

I'm unaware of any algae that can live in ice but not in water so In the context of an ice matrix 'ice algae' and 'algae' become synonyms. Consequently, I have no problem with either term within these Standard Names. If asked to come off the fence I would go for 'algae'.

The 'sea water' versus 'water' issue is nothing new. I remember unsuccessfully arguing for the use of 'water body' (the term I was using and is still used in the NVS P01 vocabulary) at a meeting in Seattle in 2008.

**Comment by letitede** [comment]
Dear all,
Thank you for your comments. I’m fine with whichever convention you prefer.
Roy is right—ice algae are phytoplankton species that survive and thrive in sea ice, unlike many other phytoplankton. As long as the sea ice environment is clear, "algae" alone is sufficient. However, I previously suggested using "ice algae" to avoid ambiguity, as "algae" is a broad term that includes phytoplankton, benthic species, and others on land. Within the sea-ice community, we rarely refer to them simply as “algae” only, even if the context is clear.
I hope this helps.
Kind regards,
Letizia

**Comment by JonathanGregory** [comment]
Dear all

I tend to agree with Karl, Luke and Roy in preferring just `algae`, since their being within sea ice is certainly clear from these standard names. Following Luke's last point, it would be peculiar to talk about `non_ice_algae` in sea ice. However, I'm interested in Letizia's comment that sea-ice scientists call them "ice algae". In a paper, would you write, "We found the concentration of ice algae in the ice to be X," for instance? If you would, is it because you envisage the possibility of any other kind of algae being there?

Best wishes

Jonathan

**Comment by letitede** [comment]
Dear Jonathan,

Thank you for your feedback.

I would use "We found the concentration of ice algae in sea ice to be X" instead of "We found the concentration of algae in sea ice to be X." Although both are technically correct, I believe the former is more precise. The term algae is very general, whereas sea ice algae (or ice algae, when the context of sea ice is already established) specifies those particular algae adapted to live in the sea ice environment.

This distinction is important because several species of phytoplankton that become entrapped in sea ice eventually perish, as they are not genetically tuned or lack acclimation strategies to survive in such harsh conditions. By using ice algae, we emphasize that these are the algae capable of thriving within sea ice, highlighting their adaptations and ecological significance.

I hope this helps clarify my preference.

Best wishes,
Letizia

**Comment by roy-lowry** [comment]
I expressed my preference before Letizia's statement that 'ice algae' is the term commonly used in the sea-ice community. My belief that community vocabulary should be used in Standard Names plus the point that algae trapped in the ice which don't survive are not considered part of the 'ice algae' sways my preference the other way.

It goes without saying that a definition of the term 'ice algae' would have to be included in the Standard Name description.

**Comment by JonathanGregory** [comment]
Dear Letizia

Thanks for the clarification. That's a good reason to use `ice_algae` in the standard name. I am happy to change my mind, along with Roy.

Best wishes

Jonathan

**Comment by lhmarsden** [comment]
I also agree

**Comment by davidhassell** [comment]
I've just caught up on this interesting thread - I also agree that `ice_algae` is good for the standard name.

**Comment by efisher008** [comment]
Dear @letitede,

I have added your proposed names (preserving the history as well as their current versions) into the CF editor. The terms are viewable here:

- `sea_ice_mass_content_of_ice_algae_expressed_as_chlorophyll`: https://cfeditor.ceda.ac.uk/proposal/5473

- `sea_ice_mole_content_of_ice_algae_expressed_as_carbon`: https://cfeditor.ceda.ac.uk/proposal/5474

- `mole_amount_of_nitrate_in_sea_ice`: https://cfeditor.ceda.ac.uk/proposal/5477

- `sea_ice_mole_content_of_silicon`: https://cfeditor.ceda.ac.uk/proposal/5478

- `gross_primary_productivity_of_biomass_expressed_as_carbon_due_to_ice_algae_in_sea_ice`: https://cfeditor.ceda.ac.uk/proposal/5476

Karl pointed out that a definition of (sea) ice algae would be necessary in the descriptions of all proposed names containing this phrase. Would you like to modify your below explanation in any way to construct this?

_Sea ice algae (or ice algae, when the context of sea ice is already established) specifies those particular algae adapted to live in the sea ice environment. This distinction is important because several species of phytoplankton that become entrapped in sea ice eventually perish, as they are not genetically tuned or lack acclimation strategies to survive in such harsh conditions. By using ice algae, we emphasize that these are the algae capable of thriving within sea ice, highlighting their adaptations and ecological significance._

There are also some phrases from the CF phrase list which I would suggest adding. These are:
- _"Content" indicates a quantity per unit area._ 
- _The phrase "expressed_as" is used in the construction "A_expressed_as_B", where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A._ 
- _The "sea_ice content" of a quantity refers to the vertical integral from the surface down to the bottom of the sea ice. "Sea ice" means all ice floating in the sea which has formed from freezing sea water, rather than by other processes such as calving of land ice to form icebergs._ 
- (for chlorophyll name) _Chlorophylls are the green pigments found in most plants, algae and cyanobacteria; their presence is essential for photosynthesis to take place. There are several different forms of chlorophyll that occur naturally. All contain a chlorin ring (chemical formula C20H16N4) which gives the green pigment and a side chain whose structure varies. The naturally occurring forms of chlorophyll contain between 35 and 55 carbon atoms._
- (for nitrate name) _The chemical formula for the nitrate anion is NO3-._
- _"Production of carbon" means the production of biomass expressed as the mass of carbon which it contains. Gross primary production is the rate of synthesis of biomass from inorganic precursors by autotrophs ("producers"), for example, photosynthesis in plants or phytoplankton. The producers also respire some of this biomass and the difference is "net_primary_production". "Productivity" means production per unit area._ 

Best,
Ellie

**Comment by letitede** [comment]
Dear Ellie,
Thank you for your message.
Here is a slightly revised version:
"Sea-ice algae (or simply 'ice algae' when the context of sea ice is clear) refer to algae uniquely able to thrive within the sea-ice environment. This distinction from phytoplankton is essential, as several phytoplankton species that become trapped in sea ice eventually perish due to a lack of genetic adaptation or acclimation strategies to survive such conditions. By referring to 'sea-ice algae,' we highlight these algae's specific features and ecological significance within the sea-ice habitat."
Regarding your other suggestions, I agree with them.
Thank you!
Kind Regards,
Letizia

**Comment by efisher008** [comment]
Hi Letizia @letitede,

Thank you for the updated description for `ice_algae`. I have added this as a phrase to the CF phrase list, and also added the approved suggested text into the standard name descriptions. 

I think we can now start the countdown to acceptance, as it seems as though this issue has reached consensus. If there are no further comments in the next 7 days, these names will be accepted and published in the next standard name table v87, planned for mid-November. Thanks again for your proposal.

Best wishes,
Ellie

**Comment by efisher008** [comment]
Hi Letizia @letitede,

As 7 days have passed with no further comment, I think we can consider these standard names as accepted. They will be published in the next version of the standard names table, which is scheduled for release in mid-November. Thanks again!

Best wishes,
Ellie

**Comment by letitede** [comment]
Thank you so much, Ellie!

Kind Regards,
Letizia



-------- Original message --------
From: Ellie Fisher ***@***.***>
Date: 04/11/2024 20.56 (GMT+02:00)
To: cf-convention/vocabularies ***@***.***>
Cc: Tedesco Letizia ***@***.***>, Mention ***@***.***>
Subject: Re: [cf-convention/vocabularies] Standard names: Propose new names for sea ice biogeochemical parameters for use in SIMIP and CMIP7 (Issue #223)


Hi Letizia @letitede<https://github.com/letitede>,

As 7 days have passed with no further comment, I think we can consider these standard names as accepted. They will be published in the next version of the standard names table, which is scheduled for release in mid-November. Thanks again!

Best wishes,
Ellie

**Comment by japamment** [comment]
All the names proposed here have been published in V87 of the standard name table, so closing this issue now.
