### ISSUE TITLE
 Standard names: iceberg_transport_across_line

### ISSUE THREAD

**Issue by mankoff** [cf-convention/vocabularies#235]
**Proposer's name** Ken Mankoff

**Date** 2024-11-07

## iceberg_transport_across_line

**Description**: Transport across_line means that which crosses a particular line on the Earth's surface; formally this means the integral along the line of the normal component of the transport. "Iceberg" means all ice floating in the sea which has formed from calving of land ice, rather than by other processes such as freezing sea water.

**Units**: kg s-1

From:  https://github.com/orgs/cf-convention/discussions/388  except that upon further reflection of that discussion, I believe that `land_ice_transport_across_line` and `land_ice_transport_across_grounding_line` are not needed due to `tendency_of_land_ice_mass`. 

Furthermore, the original request was for icebergs at their calving location, which I now find is handled by `tendency_of_land_ice_mass_due_to_calving`. Therefore, the above new name is not needed by me. It may be useful to others for icebergs crossing some arbitrary line in the ocean - that is, a term similar to `sea_ice_transport_across_line`.

**Comment by JonathanGregory** [comment]
Thanks for helping CF, Ken @mankoff! Since you _almost_ have a use-case for this quantity, and it seems likely that it will be needed by someone, and it follows an existing pattern, and you've gone to the effort of making the proposal, I think we should add it.

**Comment by taylor13** [comment]
I too support the proposal, but was wondering why we shouldn't be more specific and include "mass" in the definition, that is ``iceberg_mass_transport_across_line``. 

I noticed that we haven't been completely consistent in whether we should use "mass_transport" or "transport" alone when we mean "mass transport".  When it isn't _mass_ transport, I think we state what type of transport we're talking about (e.g., volume transport or heat transport).  Otherwise, we typically presume the term "transport" means "mass transport" (e.g., ``eastward_atmosphere_water_vapor_transport_across_unit_distance``).   If that's the case why do the following names include "mass"?

upward_ocean_mass_transport
carbon_mass_transport_in_river_channel	
nitrogen_mass_transport_in_river_channel	
phosphorus_mass_transport_in_river_channel	
silicate_mass_transport_in_river_channel	
square_of_upward_ocean_mass_transport	
ocean_mass_x_transport_due_to_advection	
ocean_mass_x_transport_due_to_advection_and_parameterized_eddy_advection
ocean_mass_y_transport_due_to_advection
ocean_mass_y_transport_due_to_advection_and_parameterized_eddy_advection

Despite these inconsistencies I'm o.k. with omitting "mass" if we include in the description (of all such variables) a sentence something like:   "Transport", as used here, means "mass transport".

**Comment by mankoff** [comment]
I based this name off of `sea_ice_transport_across_line`.

I note mass is in units so it might be redundant to have it in the name? Or if having it in units justifies having it in the name, then should "_per_unit_time" also be in the name?

**Comment by taylor13** [comment]
Yes, you've been completely consistent with past practice.  No need for you to do anything more.  

I'm suggesting, however, that it would be good for us to include for all our existing "mass transport" names, when "mass" is omitted from the name, that "transport" means "mass transport" (and not something like "volume transport").  As you say, you can infer that from the units, but I think it would be helpful to point this out in the description of the variables too.  

This is not your responsibility, since it applies to multiple existing standard names.

**Comment by efisher008** [comment]
Dear Ken @mankoff, Karl @taylor13,

Thank you for the discussion. The name has been kept as `iceberg_transport_across_line` and the following line added to the description: _"Transport", as used here, means "mass transport"_. This can be added to the CF phraselist for terms which include "transport" without the qualifying "mass". I will start the countdown to acceptance, which is 7 days with no further changes. 

It sounds like a new issue is needed to discuss the changes to the existing `mass_transport` names / transport names omitting `mass`. I am happy to open this if @taylor13 and @JonathanGregory have no objections. 

Best wishes,
Ellie

**Comment by japamment** [comment]
The name discussed here is now in the published standard name table, so closing this issue as complete.

**Comment by taylor13** [comment]
@efisher008 (cc @JonathanGregory)   .  As mentioned [here](https://github.com/cf-convention/vocabularies/issues/235#issuecomment-2494268529) and if it hasn't already been done, could you go ahead and open a new issue to clarify what is meant by "transport" when that term is used in standard names?   Thanks.
