### ISSUE TITLE
 Standard names: *Propose a new physical parameter for net radiation at surface*

### ISSUE THREAD

**Issue by YueLi92** [cf-convention/vocabularies#237]
CMIP7 Land & Land Ice Data Request Author Team
Net radiation flux at the surface
Proposer's name: Yue Li
Date: Nov 13, 2024

Based on the recent literature, https://gmd.copernicus.org/articles/17/1869/2024/, there is no standard name to represent the net radiation flux at the surface (should be identical to the sum of the net shortwave radiation and net longwave radiation at the surface). This would be important for the L&LI data request opportunity.

Please find the proposed new standard names of net radiation at the surface below. Thank you!

- Term Long Name Units

srfrad, surface_net_radiation_flux, W m-2
Net radiative flux at the surface

**Comment by JonathanGregory** [comment]
@YueLi92. Thanks for your posting. Actually there is a standard name `surface_net_downward_radiative_flux`, which is the sum of `surface_net_downward_shortwave_flux` and `surface_net_downward_longwave_flux`. Is that what you mean?

**Comment by YueLi92** [comment]
@JonathanGregory Yes, thank you. It is what I need. But it does not have a short variable name in the Data Request database. So I propose a short name "srfrad" in the Airtable. This case can be closed now.

**Comment by taylor13** [comment]
this is outside the responsibility of CF, but past experience suggests that rather than requesting *net* radiation, you should instead request the upwelling and downwelling SW and LW flux components.  This provides a much richer opportunity for analysis (e.g., enabling evaluation of the surface albedo.  For an energy budget analysis of the ice, you would also need, of course, the latent and sensible heat flux components.  Bottom line is that I would suggest replacing the net radiative flux with all of the surface heat flux components, rather than the sum of a few of them.

**Comment by YueLi92** [comment]
@taylor13 Thank you. We actually got feedback from the modeling center that requiring all the shortwave, longwave downward and upward radiation is very tedious especially for 3hr output. The output will occupy a significant storage space. Thus, we only require a full set of radiation output as the priority 2 rather than priority 1, due to the storage consideration.

**Comment by JonathanGregory** [comment]
Thanks for your replies, @YueLi92. If I understand you correctly, you _don't_ need a new standard name, because you can use `surface_net_downward_radiative_flux`. You _do_ want a CMIP short name for the quantity, but that's not something CF can help with. If that's all correct then, as you say, we can close this issue now.
