### ISSUE TITLE
 Standard names: proposal to add three new concepts related to seabed stress

### ISSUE THREAD

**Issue by danibodc** [cf-convention/vocabularies#241]
We have received a request for some new standard names from a colleague Lucy Bricheno who is producing various model outputs of seabed stress. 

**Proposer** - Danielle Wright (NOC BODC) on behalf of Lucy Bricheno (NOC MSM)*

**Date** 05/12/2024

**- Term** sea_bed_downward_stress 

**- Description** Ocean processes such as waves and currents can generate forces (or stress) on the sea bed. The surface called "sea bed" means the lower boundary of the ocean. "Stress" means the shear stress (force per unit area) exerted at the sea bed. A downward stress is a downward flux of momentum. "Downward" indicates a vector component which is positive when directed downward (as the water is acting on the sea bed). 

**- Units** N m-2.
------------------------------------------------------------------------------------------------------------------------------------------------

**- Term** sea_bed_downward_stress_due_to_dissipation_of_sea_surface_waves

**- Description** Ocean processes such as waves and currents can generate forces (or stress) on the sea bed. The surface called "sea bed" means the lower boundary of the ocean. "Stress" means the shear stress (force per unit area) exerted at the sea bed. A downward stress is a downward flux of momentum. "Downward" indicates a vector component which is positive when directed downward (as the water is acting on the sea bed). The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. The phrase "dissipation_of_sea_surface_waves" means the stress associated with sea surface waves dissipation processes through bottom friction.

**- Units** N m-2.
------------------------------------------------------------------------------------------------------------------------------------------------

**- Term** sea_bed_downward_stress_due_to_dissipation_of_ocean_current

**- Description** Ocean processes such as waves and currents can generate forces (or stress) on the sea bed. The surface called "sea bed" means the lower boundary of the ocean. "Stress" means the shear stress (force per unit area) exerted at the sea bed. A downward stress is a downward flux of momentum. "Downward" indicates a vector component which is positive when directed downward (as the water is acting on the sea bed). The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. The phrase "dissipation_of_ocean_current" means the stress associated with ocean current dissipation processes through bottom friction.

**- Units** N m-2.

**Comment by JonathanGregory** [comment]
Dear Danielle @danibodc 

Thanks for the proposal. I have some questions:

* Are these scalar quantities or components of vectors? In the former case, we probably need to insert `magnitude_of`;  in the latter case they should be `donward_eastward` and `downward_northward`.
* For consistency with existing standard names, they should say `sea_floor` rather than `sea_bed`.
* I feel that `due_to_friction` would be clearer than `due_to_dissipation_of_ocean_current`.

Best wishes

Jonathan

**Comment by bricheno** [comment]
Hi Jonathan, Danielle, 

Thanks for getting this submitted. Agree to these suggestions. These stresses are scalar, so agree with the **magnitude_of** approach, and sea_floor makes good sense. It is not clear to me how best to distinguish between the sub levels of wave and current or combined stresses? The forces from wave and currents are both being dissipated by friction, but it is the source of the energy/ driver which is different.

**Comment by bricheno** [comment]
perhaps removing the dissipation entirely, and defining only the source of the force is better? 

magnitude_of_sea_bed_downward_stress
magnitude_of_sea_bed_downward_stress_due_to_sea_surface_waves
magnitude_of_sea_bed_downward_stress_due_to_ocean_current

What do you think?
Lucy

**Comment by JonathanGregory** [comment]
Dear Lucy @bricheno 

Yes, that approach would work, I think. For the first one, `magnitude_of_sea_floor_downward_stress`  would be consistent with other standard names; there are several with `sea_floor`, and there is also `magnitude_of_surface_downward_stress`.

In practice, how are you distinguishing between these contributions to the stress? I'm still not clear how you identify which part of the sea water velocity at the sea floor is due to sea surface waves.

Best wishes

Jonathan

**Comment by bricheno** [comment]
Jonathan, I suppose the best way to describe it, is that the waves are exerting stress through an *orbital* velocity. Waves generate circular movement in the water column, which becomes more flattened due to interaction with the bottom. The effect is, that even though the waves aren't actually moving water anywhere, this back-and-forth motion still exerts a seabed stress. The currents, on the other hand do exert flow ( can be unidirectional, or oscillating tidal). This is an important difference for e.g. sediment -  while waves can resuspend sediments, it is the currents that transport.

It is possible this is a little artificial, as it is coming from a model. But there are equivalents in observations - e.g. bottom landed Benthic Acoustic Stress Sensor which provide high-frequency data. I think that there is also a divide in the energy frequency spectrum - near-bottom high-frequency pressure fluctuations are primarily due to surface waves, while currents evolve over longer timescales. so this could be though of as dividing the process in the frequency space - like for an energy density spectrum?

Lucy

**Comment by JonathanGregory** [comment]
Generally we focus on the use-cases we have, and not worry so much about possible requirements in the future! If this distinction were needed for observations, it would have to be done in another way, such as using the frequency, which we discussed earlier. Alternatively if someone thought in future of a distinction which worked equally well for both obs and models, we could rename the standard name with `due_to_model_sea_water_velocity` by using an alias. There are a few other standard name which mention `model`.

I've just remembered that I had another point to raise---sorry for further complication! I think the stress you have in mind is the magnitude of the horizontal vector composed of the downward northward stress (the downward flux of northward momentum) and the downward eastward stress (or `x` and `y`, if not north/east). Is that right? The vector is the downward flux of horizontal momentum. It seems natural to call this "downward" stress, but is "downward" necessary, since it's an absolute value? (with no direction). The sea floor and the water experience the same magnitude of stress. Would it be correct and sufficient to call it `sea_floor_horizontal_stress`, without the `magnitude_of_`, which I suggested?

**Comment by bricheno** [comment]
yes, the downward could be dropped, as it's just a scalar. So are we converging on something like this? 

sea_floor_horizontal_stress
sea_floor_horizontal_stress_due_to_sea_surface_waves
sea_floor_horizontal_stress_due_to_sea_water_velocity

**Comment by JonathanGregory** [comment]
Thanks, Lucy. Yes, I think `sea_floor_horizontal_stress` and `sea_floor_horizontal_stress_due_to_sea_surface_waves` would be good. For your use-case I do think we must be clear about the distinction between the effect of waves and other things. As we've discussed, we could do that by including `model` in `sea_floor_horizontal_stress_due_to_`**model**`_sea_water_velocity`. We can say in the description that this quantity does not include the stress due to any motions of the sea water that are not represented in the model sea water velocity. Would that be a correct description of the case? I appreciate your concern about not precluding future use for observational data. If there is a future use-case for that, we will think again. I'm confident something appropriate could be devised!

**Comment by bricheno** [comment]
Ok, I'm happy to go ahead with _model_ as you suggest.

**Comment by JonathanGregory** [comment]
Dear Lucy

Thanks for your flexibility! Please could you post a new version of the standard names and their descriptions, that you and I have agreed? Maybe others will comment, and it would help the standard names team too.

Best wishes

Jonathan

**Comment by JonathanGregory** [comment]
Lucy has opened a new issue #244 with the modified proposed we discussed here, so I'll close this one. Thanks, Lucy @bricheno.
