### ISSUE TITLE
 Standard names: *Friction Velocity in Sea Water*

### ISSUE THREAD

**Issue by abiardeau** [cf-convention/vocabularies#39]
Hello,
I am Aurore BIARDEAU from Mercator Ocean international, working for Copernicus Marine service.
Date : 13-05-2024

We are in the process of implementing a new variable in the Copernicus Marine service and we would be happy to have your feedback on our proposal :

**standard_name** : `eastward_friction_velocity_in_sea_water` (same for northward) 
(Inspired by existing standard_name `eastward_friction_velocity_in_air`)

**unit** : m s-1

I can provide more information from my expert colleagues if needed,
Kind regards,
Aurore

**Comment by abiardeau** [comment]
Hello @efisher008 
Thanks for your message. 

I also prefer `eastward_friction_velocity_at_sea_water_surface/northward_friction_velocity_at_sea_water_surface` for the names.

About the definition, we propose this one, which is coherent with the definition of `eastward_friction_velocity_in_air` : 

A velocity is a vector quantity. 
"Eastward" indicates a vector component which is positive when directed eastward (negative westward). 
Friction velocity is a reference ocean velocity derived from the relationship between ocean density and downward stress and is usually applied at a level close to the surface where stress is assumed to be independent of height and approximately proportional to the square of mean velocity.

**Comment by efisher008** [comment]
Hello @abiardeau,

Yes, this sounds reasonable. I have added those descriptions and altered the names in the editor, visible here:
`eastward_friction_velocity_at_sea_water_surface` - https://cfeditor.ceda.ac.uk/proposal/5340/edit
`northward_friction_velocity_at_sea_water_surface` - https://cfeditor.ceda.ac.uk/proposal/5419/edit

I have also added the definition of friction velocity in the context of air and sea water as stated to the CF phrasebank.

Are there any further comments on this issue? Otherwise I think we can start the 7-day countdown period to acceptance.

Best wishes,
Ellie

**Comment by abiardeau** [comment]
This is fine for me, thanks Ellie !

**Comment by efisher008** [comment]
Dear Aurore @abiardeau,

I apologise for not coming back to you, it seems as though I missed accepting this proposal! Your two new proposed names have now been accepted in the CF editor and will be published in the next standard names table version, v87, currently planned for release mid-late November this year. 

Best wishes,
Ellie

**Comment by efisher008** [comment]
These names have been published in version 87 of the Standard Name table, dated 12 November 2024. I have now closed this issue as completed.
