### ISSUE TITLE
N.H. and S.H. standard regions proposal

### ISSUE THREAD

**Issue by taylor13** [cf-convention/vocabularies#64]
**Proposer's name** Karl Taylor

**Date** 5 June 2024

This is a proposal to add two "regions" to the [list of "standard regions"](https://cfconventions.org/Data/cf-standard-names/docs/standardized-region-names.html), namely "northern_hemisphere" and "southern_hemisphere".  These regions were excluded from the list because they are "regions that could be specified by coordinate ranges in CF (e.g. western hemisphere)". 

The specific use case motivating this proposal is that for CMIP7, there is a request to be able to use a single variable to report time-series of the N.H., S.H., and global mean concentrations of certain trace gases.  This could be done using the CF-recommended method by defining a latitude coordinate of length 3 with latitude coordinate bounds of [-90, 0], [-90, 90], and [0, 90] and coordinate values of, say, -45, 0, and 45.  I think, however, that it would be clearer to most users if we simply defined a region index dimension and used the ``coordinates`` attribute to point to a variable recording the names of the regions.   We can, of course, already do this legally within the convention constraints, but my understanding is that we could not identify the auxiliary coordinate variable using the ``standard_name="region"``, because currently northern_hemisphere and southern_hemisphere are not included in the standard list.  By adding these names to the CF list of standard regions, we could use the standard_name "region" in this use case, which I think is helpful.

I would note that "global" is already included as a standard region even though it can be specified by coordinate ranges, so there is a precedent for making exceptions to the rule quoted in the first paragraph above.

**Comment by japamment** [comment]
Hi Karl @taylor13

Your proposal to add  "northern_hemisphere" and "southern_hemisphere" to the [list of standardized region names](https://cfconventions.org/Data/cf-standard-names/docs/standardized-region-names.html) has received several comments of support and no one has objected. I agree that they are a sensible addition.

Since no comments have been received in this issue since June, I think the proposals can be accepted. The standardized region names will be updated at the same time as the next standard name table update, planned for November 11th-12th.

In the header text of the region list, the penultimate sentence says "We have also added names shown like this." It is not clear to me what this sentence refers to and it seems superfluous. Unless anyone objects, I will remove it when the update is done.

Best wishes,
Alison

**Comment by taylor13** [comment]
I agree that the "penultimate" sentence you refer to above should be removed.

**Comment by larsbarring** [comment]
Agree with @taylor13

**Comment by japamment** [comment]
@taylor13 @larsbarring

Many thanks for your responses. These additions to the standardized region list are accepted and will be added at the next update on 12th November.

**Comment by japamment** [comment]
The changes agreed here have been published in V5 of the standardized region list, so closing this issue now.
