### ISSUE TITLE
Reference periods for variables derived from climatology

### ISSUE THREAD

**Issue by sethmcg** [cf-convention/vocabularies#70]
There are some variables, like `air_temperature_anomaly` and `keetch_byram_drought_index`  that use a climatological variable (like monthly average air temperature or average annual precip) as an input.

The climatology itself has its reference period recorded in a bounds variable referenced by the `climatology` attribute, but that information gets lost when you calculate these derived variables.

Does CF has a mechanism for recording these climatological reference periods associated with non-climatological variables?  And if not, do we need one?

I think the answers are "no" and "yes".  Can anyone think of a way to do it within the existing rules?  And if not, are there other use cases to consider?

The only thing I've been able to come up with is that if you had an anomaly-type variable with both `bounds` and `climatology` attributes, you could assume that bounds applies to the anomaly variable and climatology to its input, but that's confusing, and I think CF forbids having both attributes on a single variable anyway.

Thoughts?

**Comment by efisher008** [comment]
This issue is considered to have been converted into a Discussion (although not reflected by GitHub as a new standalone Discussion post was created for the purpose). Therefore this issue will now be closed, as conversation is continuing on at the following link: https://github.com/orgs/cf-convention/discussions/305. The issue history and contributions will still be visible.
